---
language: python

# support minimum python versions specified here:
# https://docs.ansible.com/ansible/dev_guide/developing_modules_python3.html
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.4"

cache:
  pip: true

dist: trusty
sudo: false

before_install:
  - pip install --upgrade -r requirements.txt

install:
  # display ansible version
  - ansible --version

script:
  - tests/test-ansible

notifications:
  email:
    on_success: change
    on_failure: change

  webhooks: https://galaxy.ansible.com/api/v1/notifications/
