---
language: python

# support minimum python versions specified here:
# https://docs.ansible.com/ansible/dev_guide/developing_modules_python3.html
python:
  - "2.6"
  - "3.5"

cache:
  pip: true

# Use the new container infrastructure
distro: trusty
sudo: false

install:
  # Install ansible
  - pip install ansible
  # Check ansible version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Run the role locally
  - >
    ansible-playbook tests/test-playbook.yml -i tests/inventory -c local
        -e vagrant_user=travis -e vagrant_group=travis
  # Test role idempotence
  - >
    ansible-playbook tests/test-playbook.yml -i tests/inventory -c local
        -e vagrant_user=travis -e vagrant_group=travis
      | tee /tmp/idempotence.txt
  - >
    tail /tmp/idempotence.txt | grep grep -q 'changed=0.*failed=0' &&
      ( echo 'Idempotence Test: Pass' && exit 0) ||
      ( echo 'Idempotence Test: Fail' && exit 1)

  # TODO add Goss tests!
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
